### ISSUE TITLE
Published

### ISSUE THREAD

**Issue by lv2eof** [brtmr/podfox#10]
Hi,
I assume the that the field "published" of the "feed.json" file represents a time. Is it?
In that case, I would like to know:
1 - Which time is it?
2 - How can I convert it to a readable date and time?
Thanks in advance.
Cheers,
Luis

**Comment by brtmr** [comment]
Hi. It's the unixtime of the publishing date.
In Python you can do this:
https://stackoverflow.com/questions/3682748/converting-unix-timestamp-string-to-readable-date-in-python
