### ISSUE TITLE
default title?

### ISSUE THREAD

**Issue by Waples** [brtmr/podfox#20]
for a feed like this:
https://media.acast.com/lukeandpete/episode61-theresatoadinmysuitcase-whatamigonnado-/media.mp3

it always names the file media, which overwrites my podcasts.. 

Is there a possibility you can change this somehow?

**Comment by Waples** [comment]
Looking through the code, why don't we use the episode title from the json-file to name the episode?

**Comment by c02y** [comment]
Agreed, podfox should pick up the title for every episode and rename the audio file with the title.

**Comment by Waples** [comment]
@c02y I have been working on my own podcast downloader, very much based on podfox.
I have included default file names in this. Currently hosting it on a private gitlab server, but when I port it over to github, I'll send you a message!

**Comment by Waples** [comment]
(also I've included threading / async)

**Comment by Waples** [comment]
@c02y code is here => https://github.com/Waples/podcrow
I didn't package anything yet 'cause I'm lazy

**Comment by c02y** [comment]
@Waples podfox contains several bugs, it is basically unusable for me, I already used another tool called [upodder](https://github.com/m3nu/upodder) to get what I wanted.

**Comment by Waples** [comment]
Closing this, build my own podcast downloader now. Thanks for the inspiration though.

**Comment by c02y** [comment]
Is it open-sourced? Would you like to share the link?

Although I don't need it right now.
