### ISSUE TITLE
Episodes

### ISSUE THREAD

**Issue by lv2eof** [brtmr/podfox#7]
Hi,
Nice your program.
A good balance between features and length.
I don't know a lot of Python although I intend to improve my skills.
So, when I enter the command "podfox episodes <shortname>" the first column is very small to my needs.
I think this can be solved with just one or two modifications to the code, but I can't figure where.
I already made one or two tries, but with no results.
Can you tell me please what I should change in order to have a larger first column.
Thanks in advance.
Cheers,
Luis

**Comment by tmajibon** [comment]
Lines 269 and 273, the 40 in both cases is the cutoff of the line.

In 269, I believe it's jumping to just past character position 40 to insert the pipe.

In 273, it's limiting the title field to no more than 40 characters.

Perhaps this could be modified in some fashion to incorporate terminal width when doing the positioning.

**Comment by lv2eof** [comment]
Hi,
Thanks.
I'll try that.
Cheers,
Luis
