### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by lv2eof** [brtmr/podfox#8]
Hi,
This is an issue :)
If I already have downloaded all the episodes for a feed and if I enter the command "podfox download" it will download again the last five episodes (at this moment I only have one feed).
I think it would be nice and easy to say "No new episodes to download.".
When I improve my skills, maybe I can try to manage this :)
Anyway, I think it would be a nice improvement to the base version.
Cheers,
Luis

**Comment by tmajibon** [comment]
Were these episodes downloaded with podfox or separately?

Just to clarify, is it re-downloading the last five episodes, or are you referring to the fact that it downloads the last 5 episodes that haven't already been downloaded? (ie. on second run, downloads 6th-10th most recent episodes)

**Comment by lv2eof** [comment]
Hi,
Ok. It wasn't what I thought :) Let me see if I can explain...
I made "podfox update", then I made "podfox episodes <shortname>" and there were two "Not Downloaded" episodes.
So, I made "podfox download" and it downloaded five episodes. I thought "Strange...".
Then I made again "podfox download" and it downloaded more five episodes :)
I thought "Something it's not working here..." and I concluded it was downloading episodes that were already downloaded.
BUT IT WAS NOT THAT.
After consulting the file "feed.json" I saw that there were 62 episodes, so it was downloading episodes not yet downloaded.
After downloading all the 62 episodes, if I make "podfox download" it doesn't download any more episodes. So this works fine.
The problem is that the listing that we obtain with "podfox episodes <shortname>" doesn't list all the episodes in the "feed.json" file.
Ok, are you sleeping already? :)
So I ask:
-Why the list that comes with "podfox episodes <shortname>" doesn't contain all the episodes in the feed?
-Is it intentional or is it a small bug? :)
Thanks in advance.
Cheers,
Luis

**Comment by tmajibon** [comment]
From what I can see, the code is limited to the first 20 entries of the episode list.

How many results are you getting with "podfox episodes" regardless of download status?

**Comment by lv2eof** [comment]
Hi,
I'm getting the twenty that you mentioned.
Ok, I understand that many podcast files become outdated after a short period, so to list very old files does't have a lot of interest.
On the other hand if the files doesn't have interest they could be deleted from disk.
But all of this are features that maybe are a bit out of the scope of a script like this.
Anyway, I think it would be nice to develop a small program with some more features.
Let's do it? :)
Cheers,
Luis

**Comment by tmajibon** [comment]
Oh, for that I just have a find command that I insert into the cron job I use with podfox:

find /podcast/directory -mtime +30 -type f -not -name "*.json" -delete

Which will delete all files that are over 30 days old. You can change the 30 to whatever number you like, and if you rewatch things or catch up, you might change mtime to atime (mtime = modified time, atime = access time)

It wouldn't be hard to add such a function, and it would be nice to at least have an option to not download listings that are beyond a certain age.

**Comment by lv2eof** [comment]
Hi,
It's a good idea.
At the moment I don't need it because I like to keep all the podcast files.
Thanks anyway.
Cheers,
Luis
